### ISSUE TITLE
TMX base?

### ISSUE THREAD

**Issue by nathanchere** [imyownyear/Z-Butt#2]
Is there any chance of a TMX base? 
A few examples:

RamaWorks: http://i.imgur.com/DPvI28s.jpg
Keyforge: https://i.redd.it/mtx82n18o1xx.jpg
Another RamaWorks: http://i.imgur.com/8TUi3Do.jpg

**Comment by imyownyear** [comment]
Just uploaded a 1u TMX StemCavity.

**Comment by nathanchere** [comment]
Thanks, I'll try it out this week and report back results :)
